env:
  es2021: true
  node: true
  browser: true
extends:
  - standard
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
rules: {
  "no-unused-vars": "off",
  "@typescript-eslint/no-unused-vars": ["error"]
}
